import type { TenantConfig } from '../tenant.types';

export const BURGERS_EXE_TENANT: TenantConfig = {
  id: 'burgers-exe',
  brandName: 'Burgers.exe',
  shortName: 'Burgers.exe',
  tagline: 'Smash Burgers Artesanales',
  categoryHeadline: 'Menú & Burgers',
  logoEmoji: '🍔',
  defaultFoodType: 'burger',
  theme: {
    accentColor: '#16A34A',
    accentColorDark: '#22C55E',
    surfaceColor: '#F5F2EE',
    surfaceCardColor: '#FFFFFF',
    accentLabel: 'Verde Bosque',
  },
  bankPayment: {
    bankName: 'BBVA',
    accountHolder: 'Burgers.exe Oficial',
    clabe: '012180000000000000',
  },
  supportPhone: '+52 55 0000 0000',
  whatsappTemplates: {
    orderGreeting: '¡Hola Burgers.exe! 👋 Quiero confirmar mi pedido:',
    paymentFollowUp: 'Hola, te contactamos de Burgers.exe sobre tu pedido:',
    orderReady: '¡Tu orden de Burgers.exe está lista! 🔥',
    orderDelivered: '¡Muchas gracias por elegir Burgers.exe! 🔥',
  },
  features: {
    rafflesAndReferrals: 'enabled',
    couponsAndPromoCodes: 'disabled',
    onlineCardPayments: 'disabled',
    liveGpsTracking: 'disabled',
    loyaltyPointsRewards: 'disabled',
    advancedWeeklyScheduling: 'enabled',
    groupOfficeOrdering: 'disabled',
    inAppLiveChatSupport: 'disabled',
    cashCutZReports: 'enabled',
    salesAnalyticsExport: 'enabled',
    inventoryWasteTracking: 'enabled',
    cfdiInvoicing: 'disabled',
    autoThermalPrinting: 'disabled',
    decoupledMultiStationKds: 'enabled',
    smsPushOrderNotifications: 'disabled',
    promotionalBanners: 'enabled',
    recipeCustomization: 'enabled',
    oneClickReorder: 'enabled',
  },
};
