import type { TenantConfig } from '../tenant.types';

export const TAMPLET_TENANT: TenantConfig = {
  id: 'tamplet',
  brandName: 'Mi Restaurante',
  shortName: 'Restaurante',
  tagline: 'Menú Digital & Pedidos',
  categoryHeadline: 'Especialidades',
  logoEmoji: '🍽️',
  defaultFoodType: 'other',
  theme: {
    accentColor: '#2563EB',
    accentColorDark: '#3B82F6',
    surfaceColor: '#F8FAFC',
    surfaceCardColor: '#FFFFFF',
    accentLabel: 'Azul Neutro',
  },
  bankPayment: {
    bankName: 'Banco',
    accountHolder: 'Titular de Cuenta',
    clabe: '000000000000000000',
  },
  supportPhone: '+52 55 0000 0000',
  whatsappTemplates: {
    orderGreeting: '¡Hola! 👋 Quiero confirmar mi pedido:',
    paymentFollowUp: 'Hola, te escribimos respecto a tu pedido:',
    orderReady: '¡Tu pedido está listo! ✨',
    orderDelivered: '¡Muchas gracias por tu compra!',
  },
  features: {
    rafflesAndReferrals: 'coming-soon',
    couponsAndPromoCodes: 'coming-soon',
    onlineCardPayments: 'coming-soon',
    liveGpsTracking: 'coming-soon',
    loyaltyPointsRewards: 'coming-soon',
    advancedWeeklyScheduling: 'enabled',
    groupOfficeOrdering: 'coming-soon',
    inAppLiveChatSupport: 'coming-soon',
    cashCutZReports: 'coming-soon',
    salesAnalyticsExport: 'coming-soon',
    inventoryWasteTracking: 'coming-soon',
    cfdiInvoicing: 'coming-soon',
    autoThermalPrinting: 'coming-soon',
    decoupledMultiStationKds: 'enabled',
    smsPushOrderNotifications: 'coming-soon',
    promotionalBanners: 'enabled',
    recipeCustomization: 'enabled',
    oneClickReorder: 'enabled',
  },
};
