name = "amsi-tortas-public-preview"
compatibility_date = "2026-05-27"
main = "functions/api/[[route]].ts"

[[d1_databases]]
binding = "BOG_MENU_DB"
database_name = "amsi-tortas-menu-preview"
database_id = "0515d9b8-aa05-4057-bfe4-999be2e56e5f"

[[r2_buckets]]
binding = "BOG_MENU_ASSETS"
bucket_name = "amsi-tortas-assets-preview"

[vars]
ENVIRONMENT = "preview"
ORDERS_V2_WRITE_ENABLED = "true"
APP_TENANT = "amsi-tortas"
