import type { DesignSpecification } from "../types/design";

export const DEFAULT_STUDIO_DESIGN_SPEC: DesignSpecification = {
  metadata: {
    version: "2.0.0",
    exportSource: "Burgers.exe Studio",
    timestamp: 1785271132030,
  },
  globalTheme: {
    spacingMode: "COMFORTABLE",
    moduleVerticalGapDp: 10,
    horizontalMarginDp: 12,
    cardPaddingDp: 10,
    primaryColor: "#16A34A",
    backgroundColor: "#F5F2EE",
  },
  contentReferences: {
    banners: {
      b1: { id: "b1", title: "⚡ ENVÍO GRATIS $0", isClickable: true },
      b2: { id: "b2", title: "🔥 DOBLE SMASH 2x1", isClickable: true },
      b3: { id: "b3", title: "🎟️ GRAN SORTEO DE COMBOS", isClickable: true },
    },
    categories: [
      "📖 Todo",
      "🔥 Combos",
      "🍔 Burgers",
      "🍟 Guarniciones",
      "🥤 Bebidas",
      "🍦 Postres",
    ],
  },
  layout: [
    {
      id: "27964523-09c4-44e0-99c8-2d3d4638fc7e",
      type: "header",
      title: "Burgers.exe",
      subtitle: "Smash Burgers Artesanales",
      variant: "DELIVERY_STANDARD",
      visible: true,
      bgColor: "var(--color-surface)",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "8b7eaac7-ffd5-496f-8cd1-52b870399fde",
      type: "banner_carousel_1",
      title: "Promociones Destacadas",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "transparent",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "c499a988-bf3c-4f1e-a2ea-f9b67a143efb",
      type: "reorder",
      title: "1-Click Reorder",
      subtitle: "Repetir último pedido",
      variant: "DEFAULT",
      visible: true,
      bgColor: "var(--color-surface)",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "93d71ec3-e80f-4333-871d-c692e6b75a85",
      type: "categories_horizontal",
      title: "Categorías Sticky",
      subtitle: "",
      variant: "VERTICAL_LIST",
      visible: true,
      bgColor: "transparent",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "e22c59db-cdef-4f22-9d3d-b3c0b886b921",
      type: "featured",
      title: "⭐ Los Más Pedidos",
      subtitle: "Nuestra selección smash artesanal",
      variant: "DEFAULT",
      visible: true,
      bgColor: "transparent",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "6031ea5d-b1f8-4771-838b-3f9675551010",
      type: "catalog",
      title: "Menú Completo",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "transparent",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
      density: "TWO_COLUMNS",
    },
    {
      id: "2facbaf9-b372-4274-9461-5e46665a1629",
      type: "cart_bar",
      title: "Barra Carrito Flotante",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "transparent",
      textColor: "var(--color-text-primary)",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
  ],
};
