import type { DesignSpecification } from "../types/design";

export const DEFAULT_STUDIO_DESIGN_SPEC: DesignSpecification = {
  metadata: {
    version: "2.0.0",
    exportSource: "Burgers.exe Studio",
    timestamp: 1785271132030,
  },
  globalTheme: {
    spacingMode: "COMFORTABLE",
    moduleVerticalGapDp: 10,
    horizontalMarginDp: 12,
    cardPaddingDp: 10,
    primaryColor: "#00FF66",
    backgroundColor: "#0B0B0B",
  },
  contentReferences: {
    banners: {
      b1: { id: "b1", title: "🔥 COMBO OVERCLOCK 2x1", isClickable: true },
      b2: { id: "b2", title: "🎮 BUNDLE GAMER NIGHT", isClickable: false },
      b3: { id: "b3", title: "⚡ ENVÍO GRATIS $0", isClickable: true },
      b2_1: { id: "b2_1", title: "🎟️ GRAN SORTEO PS5 PRO", isClickable: true },
      b2_2: { id: "b2_2", title: "🎁 GANA $1,000 EN CRÉDITO", isClickable: false },
      b3_1: { id: "b3_1", title: "💥 DÚO CYBERPUNK BUNDLE", isClickable: true },
    },
    categories: [
      "📖 Todo",
      "🔥 Combos",
      "🍔 Burgers",
      "🍟 Guarniciones",
      "🥤 Bebidas",
      "🍦 Postres",
    ],
  },
  layout: [
    {
      id: "27964523-09c4-44e0-99c8-2d3d4638fc7e",
      type: "header",
      title: "Header Navigation",
      subtitle: "Ready to play?",
      variant: "DELIVERY_STANDARD",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "8b7eaac7-ffd5-496f-8cd1-52b870399fde",
      type: "banner_carousel_1",
      title: "Carrusel Promos #1",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "c499a988-bf3c-4f1e-a2ea-f9b67a143efb",
      type: "reorder",
      title: "1-Click Reorder",
      subtitle: "Repetir último pedido",
      variant: "DEFAULT",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "60229562-1b2e-447c-9489-8eb3cc292520",
      type: "banner_carousel_2",
      title: "Carrusel Sorteos #2",
      subtitle: "",
      variant: "DEFAULT",
      visible: false,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "0a35faac-f149-42e7-a2f1-b419d91e6dba",
      type: "banner_carousel_3",
      title: "Carrusel Combos #3",
      subtitle: "",
      variant: "DEFAULT",
      visible: false,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "43e51d7e-1bc6-48fe-9f7c-8d03f7b5cd60",
      type: "burger_vs",
      title: "Burger VS & Lanzamiento",
      subtitle: "",
      variant: "DEFAULT",
      visible: false,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "93d71ec3-e80f-4333-871d-c692e6b75a85",
      type: "categories_horizontal",
      title: "Categorías Sticky",
      subtitle: "",
      variant: "VERTICAL_LIST",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "e22c59db-cdef-4f22-9d3d-b3c0b886b921",
      type: "featured",
      title: "Top Vendidos (MÁS PEDIDOS)",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
    {
      id: "6031ea5d-b1f8-4771-838b-3f9675551010",
      type: "catalog",
      title: "Grilla de Catálogo",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
      density: "TWO_COLUMNS",
    },
    {
      id: "2facbaf9-b372-4274-9461-5e46665a1629",
      type: "cart_bar",
      title: "Barra Carrito Flotante",
      subtitle: "",
      variant: "DEFAULT",
      visible: true,
      bgColor: "#121212",
      textColor: "#00FF66",
      borderRadius: 16,
      padding: 12,
      clickAction: "MOSTRAR_TOAST",
    },
  ],
};
